development: &default
  adapter: postgresql
  database: daily_specials_development
  encoding: utf8
  host: localhost
  min_messages: warning
  port: 5432
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: daily_specials_test